@startuml
'https://plantuml.com/class-diagram

abstract class TangibleAsset {
String name
int price
String color
double weight
void look()
void learn()
}

class Book extends TangibleAsset {

String isbn
void read()
}


class Computer extends TangibleAsset {

String makeName
void calculation()
}


@enduml